In [1]:
#Importamos las librerias pandas, numpy y matplotlib respectivamente
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
#Carga desde un archivo .csv sin indice
data1 = pd.read_csv('Ventas_totales.csv')

In [4]:
#Identificar valores nulos por columna
valores_nulos=data1.isnull().sum()
valores_nulos

indice_tiempo                           0
ventas_precios_corrientes               0
ventas_precios_constantes               0
ventas_totales_canal_venta              0
salon_ventas                            6
canales_on_line                         0
ventas_totales_medio_pago               0
efectivo                                0
tarjetas_debito                         1
tarjetas_credito                        7
otros_medios                            1
ventas_totales_grupo_articulos          0
subtotal_ventas_alimentos_bebidas      10
bebidas                                 1
almacen                                 2
panaderia                               1
lacteos                                 1
carnes                                  1
verduleria_fruteria                     1
alimentos_preparados_rotiseria          1
articulos_limpieza_perfumeria           0
indumentaria_calzado_textiles_hogar     2
electronicos_articulos_hogar            3
otros                                   4
dtype: int64

In [5]:
data1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 65 entries, 0 to 64
Data columns (total 24 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   indice_tiempo                        65 non-null     object
 1   ventas_precios_corrientes            65 non-null     float64
 2   ventas_precios_constantes            65 non-null     float64
 3   ventas_totales_canal_venta           65 non-null     float64
 4   salon_ventas                         59 non-null     float64
 5   canales_on_line                      65 non-null     float64
 6   ventas_totales_medio_pago            65 non-null     float64
 7   efectivo                             65 non-null     float64
 8   tarjetas_debito                      64 non-null     float64
 9   tarjetas_credito                     58 non-null     float64
 10  otros_medios                         64 non-null     float64
 11  ventas_totales_grupo_articulos       65 non-null     float64
 12  subtotal_ventas_alimentos_bebidas    55 non-null     float64
 13  bebidas                              64 non-null     float64
 14  almacen                              63 non-null     float64
 15  panaderia                            64 non-null     float64
 16  lacteos                              64 non-null     float64
 17  carnes                               64 non-null     float64
 18  verduleria_fruteria                  64 non-null     float64
 19  alimentos_preparados_rotiseria       64 non-null     float64
 20  articulos_limpieza_perfumeria        65 non-null     float64
 21  indumentaria_calzado_textiles_hogar  63 non-null     float64
 22  electronicos_articulos_hogar         62 non-null     float64
 23  otros                                61 non-null     float64
dtypes: float64(23), object(1)
memory usage: 12.3+ KB

In [6]:
#Realizamos una copia del dataframe
data1_1=data1.copy()

In [7]:
#Método de sustitución de valores nulos
#Sustituir valores nulos con promedio o media
data1["salon_ventas"]=data1["salon_ventas"].fillna(round(data1_1["salon_ventas"].mean(),1))

In [8]:
#Corroboramos valores nulos
valores_nulos=data1.isnull().sum()
valores_nulos

indice_tiempo                           0
ventas_precios_corrientes               0
ventas_precios_constantes               0
ventas_totales_canal_venta              0
salon_ventas                            0
canales_on_line                         0
ventas_totales_medio_pago               0
efectivo                                0
tarjetas_debito                         1
tarjetas_credito                        7
otros_medios                            1
ventas_totales_grupo_articulos          0
subtotal_ventas_alimentos_bebidas      10
bebidas                                 1
almacen                                 2
panaderia                               1
lacteos                                 1
carnes                                  1
verduleria_fruteria                     1
alimentos_preparados_rotiseria          1
articulos_limpieza_perfumeria           0
indumentaria_calzado_textiles_hogar     2
electronicos_articulos_hogar            3
otros                                   4
dtype: int64

In [9]:
#Método de sustitución de valores nulos
#Sustituir valores nulos por un string en  concreto 
data1["tarjetas_debito"] =data1["tarjetas_debito"].fillna("0") 
data1

,indice_tiempo,ventas_precios_corrientes,ventas_precios_constantes,ventas_totales_canal_venta,salon_ventas,canales_on_line,ventas_totales_medio_pago,efectivo,tarjetas_debito,tarjetas_credito,...,almacen,panaderia,lacteos,carnes,verduleria_fruteria,alimentos_preparados_rotiseria,articulos_limpieza_perfumeria,indumentaria_calzado_textiles_hogar,electronicos_articulos_hogar,otros
0,01/01/2017,27858.9,27477.3,2.785887e+07,2.759173e+07,2.671420e+05,2.785887e+07,1.023010e+07,6864575.384,9.047205e+06,...,6.705475e+06,9.459063e+05,2.880656e+06,2.606193e+06,1.050314e+06,3.407774e+05,4.397544e+06,7.723718e+05,1.838507e+06,2.806660e+06
1,01/02/2017,25994.2,25223.4,2.599420e+07,2.574918e+07,2.450208e+05,2.599420e+07,9.719067e+06,6438494.011,8.309150e+06,...,6.576625e+06,9.256186e+05,2.855640e+06,2.600084e+06,1.026167e+06,3.282887e+05,4.053284e+06,6.722905e+05,1.257662e+06,2.354085e+06
2,01/03/2017,27780.0,26334.3,2.778001e+07,2.747223e+07,3.077778e+05,2.778001e+07,1.024444e+07,6908522.962,8.845010e+06,...,7.437264e+06,1.016148e+06,3.188259e+06,2.824977e+06,1.075526e+06,3.533352e+05,4.354198e+06,6.676967e+05,1.305675e+06,2.266189e+06
3,01/04/2017,29134.3,27045.9,2.913427e+07,2.882748e+07,3.067927e+05,2.913427e+07,1.031263e+07,7454251.8,9.458167e+06,...,8.211244e+06,1.132396e+06,3.257140e+06,3.006159e+06,1.037213e+06,3.596945e+05,4.355707e+06,8.389482e+05,1.535726e+06,2.146756e+06
4,01/05/2017,27969.0,25631.9,2.796900e+07,2.756931e+07,3.996933e+05,2.796900e+07,1.014761e+07,6735747.319,9.220930e+06,...,7.651058e+06,1.033082e+06,3.232636e+06,2.799142e+06,9.826512e+05,3.365680e+05,4.206102e+06,9.158951e+05,1.824462e+06,2.117971e+06
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60,01/01/2022,154517.1,45463.4,1.545171e+08,1.496976e+08,4.819480e+06,1.545171e+08,4.696260e+07,46053650.13,5.404833e+07,...,3.750517e+07,4.860318e+06,1.610477e+07,1.740849e+07,6.138441e+06,1.401929e+06,2.133021e+07,3.782646e+06,1.218755e+07,1.343307e+07
61,01/02/2022,152202.6,23802.1,1.522026e+08,1.484065e+08,3.796044e+06,1.522026e+08,4.629096e+07,45283575.25,5.370589e+07,...,3.820979e+07,5.045920e+06,1.613982e+07,1.826074e+07,6.436028e+06,1.370640e+06,2.030545e+07,NaN,9.189746e+06,1.330139e+07
62,01/03/2022,16.5,24612.4,1.689825e+08,1.643211e+08,4.661350e+05,1.689825e+08,5.126208e+07,47364363.88,NaN,...,4.541886e+07,5.922820e+06,1.841916e+07,2.082760e+07,6.886240e+06,1.589119e+06,2.294201e+07,3.912852e+06,1.089879e+07,NaN
63,01/04/2022,177148.1,24140.5,1.771481e+08,1.730038e+08,4.144284e+06,1.771481e+08,5.319000e+07,50063972.79,6.535759e+07,...,4.999168e+07,6.746167e+06,1.930946e+07,2.287784e+07,6.510666e+06,1.719459e+06,2.313127e+07,4.228054e+06,NaN,1.191048e+07
64,01/05/2022,179639.2,23234.2,1.796392e+08,1.753585e+08,4.280751e+06,1.796392e+08,5.273811e+07,49886787.86,6.807009e+07,...,5.015035e+07,6.667330e+06,2.012112e+07,2.284153e+07,6.314109e+06,1.779483e+06,2.357864e+07,5.213153e+06,1.203960e+07,1.234998e+07

In [10]:
#Corroboramos valores nulos
valores_nulos=data1.isnull().sum()
valores_nulos

indice_tiempo                           0
ventas_precios_corrientes               0
ventas_precios_constantes               0
ventas_totales_canal_venta              0
salon_ventas                            0
canales_on_line                         0
ventas_totales_medio_pago               0
efectivo                                0
tarjetas_debito                         0
tarjetas_credito                        7
otros_medios                            1
ventas_totales_grupo_articulos          0
subtotal_ventas_alimentos_bebidas      10
bebidas                                 1
almacen                                 2
panaderia                               1
lacteos                                 1
carnes                                  1
verduleria_fruteria                     1
alimentos_preparados_rotiseria          1
articulos_limpieza_perfumeria           0
indumentaria_calzado_textiles_hogar     2
electronicos_articulos_hogar            3
otros                                   4
dtype: int64

In [23]:
#Método de sustitución de valores nulos
#Sustituir valores nulos por un string en  concreto 
data1["tarjetas_credito"] =data1["tarjetas_credito"].fillna("0") 
data1

,indice_tiempo,ventas_precios_corrientes,ventas_precios_constantes,ventas_totales_canal_venta,salon_ventas,canales_on_line,ventas_totales_medio_pago,efectivo,tarjetas_debito,tarjetas_credito,...,lacteos,carnes,verduleria_fruteria,alimentos_preparados_rotiseria,articulos_limpieza_perfumeria,indumentaria_calzado_textiles_hogar,electronicos_articulos_hogar,otros,tarjetas_credito,tarjetas_debito
0,01/01/2017,27858.9,27477.3,2.785887e+07,2.759173e+07,2.671420e+05,2.785887e+07,1.023010e+07,6864575.384,9047205.493,...,2.880656e+06,2.606193e+06,1.050314e+06,3.407774e+05,4.397544e+06,7.723718e+05,1.838507e+06,2.806660e+06,9047205.493,6864575.384
1,01/02/2017,25994.2,25223.4,2.599420e+07,2.574918e+07,2.450208e+05,2.599420e+07,9.719067e+06,6438494.011,8309150.301,...,2.855640e+06,2.600084e+06,1.026167e+06,3.282887e+05,4.053284e+06,6.722905e+05,1.257662e+06,2.354085e+06,8309150.301,6438494.011
2,01/03/2017,27780.0,26334.3,2.778001e+07,2.747223e+07,3.077778e+05,2.778001e+07,1.024444e+07,6908522.962,8845010.494,...,3.188259e+06,2.824977e+06,1.075526e+06,3.533352e+05,4.354198e+06,6.676967e+05,1.305675e+06,2.266189e+06,8845010.494,6908522.962
3,01/04/2017,29134.3,27045.9,2.913427e+07,2.882748e+07,3.067927e+05,2.913427e+07,1.031263e+07,7454251.8,9458166.682,...,3.257140e+06,3.006159e+06,1.037213e+06,3.596945e+05,4.355707e+06,8.389482e+05,1.535726e+06,2.146756e+06,9458166.682,7454251.8
4,01/05/2017,27969.0,25631.9,2.796900e+07,2.756931e+07,3.996933e+05,2.796900e+07,1.014761e+07,6735747.319,9220929.862,...,3.232636e+06,2.799142e+06,9.826512e+05,3.365680e+05,4.206102e+06,9.158951e+05,1.824462e+06,2.117971e+06,9220929.862,6735747.319
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60,01/01/2022,154517.1,45463.4,1.545171e+08,1.496976e+08,4.819480e+06,1.545171e+08,4.696260e+07,46053650.13,54048333.12,...,1.610477e+07,1.740849e+07,6.138441e+06,1.401929e+06,2.133021e+07,3.782646e+06,1.218755e+07,1.343307e+07,54048333.12,46053650.13
61,01/02/2022,152202.6,23802.1,1.522026e+08,1.484065e+08,3.796044e+06,1.522026e+08,4.629096e+07,45283575.25,53705893.17,...,1.613982e+07,1.826074e+07,6.436028e+06,1.370640e+06,2.030545e+07,NaN,9.189746e+06,1.330139e+07,53705893.17,45283575.25
62,01/03/2022,16.5,24612.4,1.689825e+08,1.643211e+08,4.661350e+05,1.689825e+08,5.126208e+07,47364363.88,0,...,1.841916e+07,2.082760e+07,6.886240e+06,1.589119e+06,2.294201e+07,3.912852e+06,1.089879e+07,NaN,0,47364363.88
63,01/04/2022,177148.1,24140.5,1.771481e+08,1.730038e+08,4.144284e+06,1.771481e+08,5.319000e+07,50063972.79,65357591.09,...,1.930946e+07,2.287784e+07,6.510666e+06,1.719459e+06,2.313127e+07,4.228054e+06,NaN,1.191048e+07,65357591.09,50063972.79
64,01/05/2022,179639.2,23234.2,1.796392e+08,1.753585e+08,4.280751e+06,1.796392e+08,5.273811e+07,49886787.86,68070088.23,...,2.012112e+07,2.284153e+07,6.314109e+06,1.779483e+06,2.357864e+07,5.213153e+06,1.203960e+07,1.234998e+07,68070088.23,49886787.86

In [24]:
#Corroboramos valores nulos
valores_nulos=data1.isnull().sum()
valores_nulos

indice_tiempo                           0
ventas_precios_corrientes               0
ventas_precios_constantes               0
ventas_totales_canal_venta              0
salon_ventas                            0
canales_on_line                         0
ventas_totales_medio_pago               0
efectivo                                0
tarjetas_debito                         0
tarjetas_credito                        0
otros_medios                            1
ventas_totales_grupo_articulos          0
subtotal_ventas_alimentos_bebidas      10
bebidas                                 1
almacen                                 2
panaderia                               1
lacteos                                 1
carnes                                  1
verduleria_fruteria                     1
alimentos_preparados_rotiseria          1
articulos_limpieza_perfumeria           0
indumentaria_calzado_textiles_hogar     2
electronicos_articulos_hogar            3
otros                                   4
tarjetas_credito                        0
tarjetas_debito                         0
dtype: int64

In [25]:
#Método de sustitución de valores nulos
#Sustituir valores nulos por un string en  concreto 
data1["otros_medios"] =data1["otros_medios"].fillna("0") 
data1

,indice_tiempo,ventas_precios_corrientes,ventas_precios_constantes,ventas_totales_canal_venta,salon_ventas,canales_on_line,ventas_totales_medio_pago,efectivo,tarjetas_debito,tarjetas_credito,...,lacteos,carnes,verduleria_fruteria,alimentos_preparados_rotiseria,articulos_limpieza_perfumeria,indumentaria_calzado_textiles_hogar,electronicos_articulos_hogar,otros,tarjetas_credito,tarjetas_debito
0,01/01/2017,27858.9,27477.3,2.785887e+07,2.759173e+07,2.671420e+05,2.785887e+07,1.023010e+07,6864575.384,9047205.493,...,2.880656e+06,2.606193e+06,1.050314e+06,3.407774e+05,4.397544e+06,7.723718e+05,1.838507e+06,2.806660e+06,9047205.493,6864575.384
1,01/02/2017,25994.2,25223.4,2.599420e+07,2.574918e+07,2.450208e+05,2.599420e+07,9.719067e+06,6438494.011,8309150.301,...,2.855640e+06,2.600084e+06,1.026167e+06,3.282887e+05,4.053284e+06,6.722905e+05,1.257662e+06,2.354085e+06,8309150.301,6438494.011
2,01/03/2017,27780.0,26334.3,2.778001e+07,2.747223e+07,3.077778e+05,2.778001e+07,1.024444e+07,6908522.962,8845010.494,...,3.188259e+06,2.824977e+06,1.075526e+06,3.533352e+05,4.354198e+06,6.676967e+05,1.305675e+06,2.266189e+06,8845010.494,6908522.962
3,01/04/2017,29134.3,27045.9,2.913427e+07,2.882748e+07,3.067927e+05,2.913427e+07,1.031263e+07,7454251.8,9458166.682,...,3.257140e+06,3.006159e+06,1.037213e+06,3.596945e+05,4.355707e+06,8.389482e+05,1.535726e+06,2.146756e+06,9458166.682,7454251.8
4,01/05/2017,27969.0,25631.9,2.796900e+07,2.756931e+07,3.996933e+05,2.796900e+07,1.014761e+07,6735747.319,9220929.862,...,3.232636e+06,2.799142e+06,9.826512e+05,3.365680e+05,4.206102e+06,9.158951e+05,1.824462e+06,2.117971e+06,9220929.862,6735747.319
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60,01/01/2022,154517.1,45463.4,1.545171e+08,1.496976e+08,4.819480e+06,1.545171e+08,4.696260e+07,46053650.13,54048333.12,...,1.610477e+07,1.740849e+07,6.138441e+06,1.401929e+06,2.133021e+07,3.782646e+06,1.218755e+07,1.343307e+07,54048333.12,46053650.13
61,01/02/2022,152202.6,23802.1,1.522026e+08,1.484065e+08,3.796044e+06,1.522026e+08,4.629096e+07,45283575.25,53705893.17,...,1.613982e+07,1.826074e+07,6.436028e+06,1.370640e+06,2.030545e+07,NaN,9.189746e+06,1.330139e+07,53705893.17,45283575.25
62,01/03/2022,16.5,24612.4,1.689825e+08,1.643211e+08,4.661350e+05,1.689825e+08,5.126208e+07,47364363.88,0,...,1.841916e+07,2.082760e+07,6.886240e+06,1.589119e+06,2.294201e+07,3.912852e+06,1.089879e+07,NaN,0,47364363.88
63,01/04/2022,177148.1,24140.5,1.771481e+08,1.730038e+08,4.144284e+06,1.771481e+08,5.319000e+07,50063972.79,65357591.09,...,1.930946e+07,2.287784e+07,6.510666e+06,1.719459e+06,2.313127e+07,4.228054e+06,NaN,1.191048e+07,65357591.09,50063972.79
64,01/05/2022,179639.2,23234.2,1.796392e+08,1.753585e+08,4.280751e+06,1.796392e+08,5.273811e+07,49886787.86,68070088.23,...,2.012112e+07,2.284153e+07,6.314109e+06,1.779483e+06,2.357864e+07,5.213153e+06,1.203960e+07,1.234998e+07,68070088.23,49886787.86

In [26]:
#Corroboramos valores nulos
valores_nulos=data1.isnull().sum()
valores_nulos

indice_tiempo                           0
ventas_precios_corrientes               0
ventas_precios_constantes               0
ventas_totales_canal_venta              0
salon_ventas                            0
canales_on_line                         0
ventas_totales_medio_pago               0
efectivo                                0
tarjetas_debito                         0
tarjetas_credito                        0
otros_medios                            0
ventas_totales_grupo_articulos          0
subtotal_ventas_alimentos_bebidas      10
bebidas                                 1
almacen                                 2
panaderia                               1
lacteos                                 1
carnes                                  1
verduleria_fruteria                     1
alimentos_preparados_rotiseria          1
articulos_limpieza_perfumeria           0
indumentaria_calzado_textiles_hogar     2
electronicos_articulos_hogar            3
otros                                   4
tarjetas_credito                        0
tarjetas_debito                         0
dtype: int64

In [27]:
#Método de sustitución de valores nulos
#Sustituir valores nulos con promedio o media
data1["subtotal_ventas_alimentos_bebidas"]=data1["subtotal_ventas_alimentos_bebidas"].fillna(round(data1_1["subtotal_ventas_alimentos_bebidas"].mean(),1))

In [28]:
#Corroboramos valores nulos
valores_nulos=data1.isnull().sum()
valores_nulos

indice_tiempo                          0
ventas_precios_corrientes              0
ventas_precios_constantes              0
ventas_totales_canal_venta             0
salon_ventas                           0
canales_on_line                        0
ventas_totales_medio_pago              0
efectivo                               0
tarjetas_debito                        0
tarjetas_credito                       0
otros_medios                           0
ventas_totales_grupo_articulos         0
subtotal_ventas_alimentos_bebidas      0
bebidas                                1
almacen                                2
panaderia                              1
lacteos                                1
carnes                                 1
verduleria_fruteria                    1
alimentos_preparados_rotiseria         1
articulos_limpieza_perfumeria          0
indumentaria_calzado_textiles_hogar    2
electronicos_articulos_hogar           3
otros                                  4
tarjetas_credito                       0
tarjetas_debito                        0
dtype: int64

In [29]:
#Método de sustitución de valores nulos
#Sustituir valores nulos por valores no nulos hacia adelante  "forward fill" ("ffill")
#Filtro por columnas
data1["bebidas"] =data1["bebidas"].fillna(method="ffill")

C:\Users\sarah\AppData\Local\Temp\ipykernel_19468\2593493831.py:4: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  data1["bebidas"] =data1["bebidas"].fillna(method="ffill")

In [30]:
#Corroboramos valores nulos
valores_nulos=data1.isnull().sum()
valores_nulos

indice_tiempo                          0
ventas_precios_corrientes              0
ventas_precios_constantes              0
ventas_totales_canal_venta             0
salon_ventas                           0
canales_on_line                        0
ventas_totales_medio_pago              0
efectivo                               0
tarjetas_debito                        0
tarjetas_credito                       0
otros_medios                           0
ventas_totales_grupo_articulos         0
subtotal_ventas_alimentos_bebidas      0
bebidas                                0
almacen                                2
panaderia                              1
lacteos                                1
carnes                                 1
verduleria_fruteria                    1
alimentos_preparados_rotiseria         1
articulos_limpieza_perfumeria          0
indumentaria_calzado_textiles_hogar    2
electronicos_articulos_hogar           3
otros                                  4
tarjetas_credito                       0
tarjetas_debito                        0
dtype: int64

In [33]:
#Método de sustitución de valores nulos
#Sustituir valores nulos por valores no nulos hacia adelante  "forward fill" ("ffill")
#Filtro por columnas
data1["almacen"] =data1["almacen"].fillna(method="bfill")

C:\Users\sarah\AppData\Local\Temp\ipykernel_19468\1358841385.py:4: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  data1["almacen"] =data1["almacen"].fillna(method="bfill")

In [34]:
#Corroboramos valores nulos
valores_nulos=data1.isnull().sum()
valores_nulos

indice_tiempo                          0
ventas_precios_corrientes              0
ventas_precios_constantes              0
ventas_totales_canal_venta             0
salon_ventas                           0
canales_on_line                        0
ventas_totales_medio_pago              0
efectivo                               0
tarjetas_debito                        0
tarjetas_credito                       0
otros_medios                           0
ventas_totales_grupo_articulos         0
subtotal_ventas_alimentos_bebidas      0
bebidas                                0
almacen                                0
panaderia                              1
lacteos                                1
carnes                                 1
verduleria_fruteria                    1
alimentos_preparados_rotiseria         1
articulos_limpieza_perfumeria          0
indumentaria_calzado_textiles_hogar    2
electronicos_articulos_hogar           3
otros                                  4
tarjetas_credito                       0
tarjetas_debito                        0
dtype: int64

In [37]:
#Método de sustitución de valores nulos
#Sustituir valores nulos por valores no nulos hacia adelante  "forward fill" ("bfill")
#Filtro por columnas
data1["panaderia"] =data1["panaderia"].fillna(method="bfill")

C:\Users\sarah\AppData\Local\Temp\ipykernel_19468\46944961.py:4: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  data1["panaderia"] =data1["panaderia"].fillna(method="bfill")

In [38]:
#Método de sustitución de valores nulos
#Sustituir valores nulos por valores no nulos hacia adelante  "forward fill" ("ffill")
#Filtro por columnas
data1["lacteos"] =data1["lacteos"].fillna(method="ffill")

C:\Users\sarah\AppData\Local\Temp\ipykernel_19468\2904773995.py:4: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  data1["lacteos"] =data1["lacteos"].fillna(method="ffill")

In [39]:
#Método de sustitución de valores nulos
#Sustituir valores nulos por valores no nulos hacia adelante  "forward fill" ("bfill")
#Filtro por columnas
data1["carnes"] =data1["carnes"].fillna(method="bfill")

C:\Users\sarah\AppData\Local\Temp\ipykernel_19468\617608810.py:4: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  data1["carnes"] =data1["carnes"].fillna(method="bfill")

In [40]:
#Corroboramos valores nulos
valores_nulos=data1.isnull().sum()
valores_nulos

indice_tiempo                          0
ventas_precios_corrientes              0
ventas_precios_constantes              0
ventas_totales_canal_venta             0
salon_ventas                           0
canales_on_line                        0
ventas_totales_medio_pago              0
efectivo                               0
tarjetas_debito                        0
tarjetas_credito                       0
otros_medios                           0
ventas_totales_grupo_articulos         0
subtotal_ventas_alimentos_bebidas      0
bebidas                                0
almacen                                0
panaderia                              0
lacteos                                0
carnes                                 0
verduleria_fruteria                    1
alimentos_preparados_rotiseria         1
articulos_limpieza_perfumeria          0
indumentaria_calzado_textiles_hogar    2
electronicos_articulos_hogar           3
otros                                  4
tarjetas_credito                       0
tarjetas_debito                        0
dtype: int64

In [41]:
#Método de sustitución de valores nulos
#Sustituir valores nulos con promedio o media
data1["verduleria_fruteria"]=data1["verduleria_fruteria"].fillna(round(data1_1["verduleria_fruteria"].mean(),1))

In [42]:
#Método de sustitución de valores nulos
#Sustituir valores nulos con promedio o media
data1["alimentos_preparados_rotiseria"]=data1["alimentos_preparados_rotiseria"].fillna(round(data1_1["alimentos_preparados_rotiseria"].mean(),1))

In [43]:
#Método de sustitución de valores nulos
#Sustituir valores nulos por valores no nulos hacia adelante  "forward fill" ("bfill")
#Filtro por columnas
data1["indumentaria_calzado_textiles_hogar"] =data1["indumentaria_calzado_textiles_hogar"].fillna(method="bfill")

C:\Users\sarah\AppData\Local\Temp\ipykernel_19468\757617866.py:4: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  data1["indumentaria_calzado_textiles_hogar"] =data1["indumentaria_calzado_textiles_hogar"].fillna(method="bfill")

In [44]:
#Corroboramos valores nulos
valores_nulos=data1.isnull().sum()
valores_nulos

indice_tiempo                          0
ventas_precios_corrientes              0
ventas_precios_constantes              0
ventas_totales_canal_venta             0
salon_ventas                           0
canales_on_line                        0
ventas_totales_medio_pago              0
efectivo                               0
tarjetas_debito                        0
tarjetas_credito                       0
otros_medios                           0
ventas_totales_grupo_articulos         0
subtotal_ventas_alimentos_bebidas      0
bebidas                                0
almacen                                0
panaderia                              0
lacteos                                0
carnes                                 0
verduleria_fruteria                    0
alimentos_preparados_rotiseria         0
articulos_limpieza_perfumeria          0
indumentaria_calzado_textiles_hogar    0
electronicos_articulos_hogar           3
otros                                  4
tarjetas_credito                       0
tarjetas_debito                        0
dtype: int64

In [45]:
#Método de sustitución de valores nulos
#Sustituir valores nulos con promedio o media
data1["electronicos_articulos_hogar"]=data1["electronicos_articulos_hogar"].fillna(round(data1_1["electronicos_articulos_hogar"].mean(),1))

In [46]:
#Método de sustitución de valores nulos
#Sustituir valores nulos con promedio o media
data1["otros"]=data1["otros"].fillna(round(data1_1["otros"].mean(),1))

In [47]:
#Corroboramos valores nulos
valores_nulos=data1.isnull().sum()
valores_nulos

indice_tiempo                          0
ventas_precios_corrientes              0
ventas_precios_constantes              0
ventas_totales_canal_venta             0
salon_ventas                           0
canales_on_line                        0
ventas_totales_medio_pago              0
efectivo                               0
tarjetas_debito                        0
tarjetas_credito                       0
otros_medios                           0
ventas_totales_grupo_articulos         0
subtotal_ventas_alimentos_bebidas      0
bebidas                                0
almacen                                0
panaderia                              0
lacteos                                0
carnes                                 0
verduleria_fruteria                    0
alimentos_preparados_rotiseria         0
articulos_limpieza_perfumeria          0
indumentaria_calzado_textiles_hogar    0
electronicos_articulos_hogar           0
otros                                  0
tarjetas_credito                       0
tarjetas_debito                        0
dtype: int64

In [48]:
#Corroboramos valores nulos en todo el dataframe
valores_nulos=data1.isnull().sum().sum()
valores_nulos

np.int64(0)

In [50]:
#Convertir DataFrame a CSV
data1.to_csv("Ventas_totales_LIMPIO.csv")